/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_05 (number 106), JTAG_nTRST/J16[3]/USER_LED/J17[5] */
/* Routed pin properties */
#define BOARD_USER_LED_PERIPHERAL                                          GPIO1   /*!< Peripheral name */
#define BOARD_USER_LED_SIGNAL                                            gpio_io   /*!< Signal name */
#define BOARD_USER_LED_CHANNEL                                                5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_USER_LED_GPIO                                                GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_USER_LED_GPIO_PIN                                               5U   /*!< GPIO pin number */
#define BOARD_USER_LED_GPIO_PIN_MASK                                  (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_USER_LED_PORT                                                GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_USER_LED_PIN                                                    5U   /*!< PORT pin number */
#define BOARD_USER_LED_PIN_MASK                                       (1U << 5U)   /*!< PORT pin mask */

/* GPIO_AD_B0_11 (number 97), ENET_CRS_DV/U11[18]/J19[3] */
/* Routed pin properties */
#define BOARD_ENET_CRS_DV_PERIPHERAL                                         ARM   /*!< Peripheral name */
#define BOARD_ENET_CRS_DV_SIGNAL                                   arm_trace_swo   /*!< Signal name */

/* PMIC_STBY_REQ (number 54), SD_PWREN */
/* Routed pin properties */
#define BOARD_U_LED_PERIPHERAL                                             GPIO5   /*!< Peripheral name */
#define BOARD_U_LED_SIGNAL                                               gpio_io   /*!< Signal name */
#define BOARD_U_LED_CHANNEL                                                   2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_U_LED_GPIO                                                   GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_U_LED_GPIO_PIN                                                  2U   /*!< GPIO pin number */
#define BOARD_U_LED_GPIO_PIN_MASK                                     (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_U_LED_PORT                                                   GPIO5   /*!< PORT peripheral base pointer */
#define BOARD_U_LED_PIN                                                       2U   /*!< PORT pin number */
#define BOARD_U_LED_PIN_MASK                                          (1U << 2U)   /*!< PORT pin mask */

/* GPIO_AD_B0_06 (number 105), UART1_TXD/J17[6] */
/* Routed pin properties */
#define BOARD_UART1_TXD_PERIPHERAL                                       LPUART1   /*!< Peripheral name */
#define BOARD_UART1_TXD_SIGNAL                                                TX   /*!< Signal name */

/* GPIO_AD_B0_07 (number 101), UART1_RXD/J17[4] */
/* Routed pin properties */
#define BOARD_UART1_RXD_PERIPHERAL                                       LPUART1   /*!< Peripheral name */
#define BOARD_UART1_RXD_SIGNAL                                                RX   /*!< Signal name */

/* GPIO_EMC_32 (number 124), SEMC_D8/U14[42] */
/* Routed pin properties */
#define BOARD_SEMC_D8_PERIPHERAL                                          LPSPI4   /*!< Peripheral name */
#define BOARD_SEMC_D8_SIGNAL                                                 SCK   /*!< Signal name */

/* GPIO_EMC_33 (number 123), SEMC_D9/U14[44] */
/* Routed pin properties */
#define BOARD_LCD_CS_PERIPHERAL                                           LPSPI4   /*!< Peripheral name */
#define BOARD_LCD_CS_SIGNAL                                                 PCS0   /*!< Signal name */

/* GPIO_EMC_34 (number 122), SEMC_D10/U14[45] */
/* Routed pin properties */
#define BOARD_SEMC_D10_PERIPHERAL                                         LPSPI4   /*!< Peripheral name */
#define BOARD_SEMC_D10_SIGNAL                                                SDO   /*!< Signal name */

/* GPIO_EMC_35 (number 121), SEMC_D11/U14[47] */
/* Routed pin properties */
#define BOARD_SEMC_D11_PERIPHERAL                                         LPSPI4   /*!< Peripheral name */
#define BOARD_SEMC_D11_SIGNAL                                                SDI   /*!< Signal name */

/* GPIO_EMC_36 (number 120), SEMC_D12/U14[48] */
/* Routed pin properties */
#define BOARD_LCD_DC_PERIPHERAL                                            GPIO3   /*!< Peripheral name */
#define BOARD_LCD_DC_SIGNAL                                              gpio_io   /*!< Signal name */
#define BOARD_LCD_DC_CHANNEL                                                  4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LCD_DC_GPIO                                                  GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_LCD_DC_GPIO_PIN                                                 4U   /*!< GPIO pin number */
#define BOARD_LCD_DC_GPIO_PIN_MASK                                    (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_LCD_DC_PORT                                                  GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_LCD_DC_PIN                                                      4U   /*!< PORT pin number */
#define BOARD_LCD_DC_PIN_MASK                                         (1U << 4U)   /*!< PORT pin mask */

/* GPIO_EMC_37 (number 119), SEMC_D13/U14[50] */
/* Routed pin properties */
#define BOARD_SEMC_D13_PERIPHERAL                                         LPSPI4   /*!< Peripheral name */
#define BOARD_SEMC_D13_SIGNAL                                               PCS2   /*!< Signal name */

/* GPIO_EMC_31 (number 125), SEMC_DM1/U14[39] */
/* Routed pin properties */
#define BOARD_LCD_BLK_PERIPHERAL                                           GPIO2   /*!< Peripheral name */
#define BOARD_LCD_BLK_SIGNAL                                             gpio_io   /*!< Signal name */
#define BOARD_LCD_BLK_CHANNEL                                                31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LCD_BLK_GPIO                                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_LCD_BLK_GPIO_PIN                                               31U   /*!< GPIO pin number */
#define BOARD_LCD_BLK_GPIO_PIN_MASK                                  (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_LCD_BLK_PORT                                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_LCD_BLK_PIN                                                    31U   /*!< PORT pin number */
#define BOARD_LCD_BLK_PIN_MASK                                       (1U << 31U)   /*!< PORT pin mask */

/* GPIO_EMC_39 (number 117), SEMC_D15/U14[53] */
/* Routed pin properties */
#define BOARD_LCD_RES_PERIPHERAL                                           GPIO3   /*!< Peripheral name */
#define BOARD_LCD_RES_SIGNAL                                             gpio_io   /*!< Signal name */
#define BOARD_LCD_RES_CHANNEL                                                 7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LCD_RES_GPIO                                                 GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_LCD_RES_GPIO_PIN                                                7U   /*!< GPIO pin number */
#define BOARD_LCD_RES_GPIO_PIN_MASK                                   (1U << 7U)   /*!< GPIO pin mask */
#define BOARD_LCD_RES_PORT                                                 GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_LCD_RES_PIN                                                     7U   /*!< PORT pin number */
#define BOARD_LCD_RES_PIN_MASK                                        (1U << 7U)   /*!< PORT pin mask */

/* GPIO_EMC_10 (number 7), SEMC_CAS/U14[17] */
/* Routed pin properties */
#define BOARD_SEMC_CAS_PERIPHERAL                                         LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_CAS_SIGNAL                                                SCK   /*!< Signal name */

/* GPIO_EMC_11 (number 4), SEMC_RAS/U14[18] */
/* Routed pin properties */
#define BOARD_SEMC_RAS_PERIPHERAL                                         LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_RAS_SIGNAL                                               PCS0   /*!< Signal name */

/* GPIO_EMC_12 (number 3), SEMC_CS0/U14[19] */
/* Routed pin properties */
#define BOARD_SEMC_CS0_PERIPHERAL                                         LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_CS0_SIGNAL                                                SDO   /*!< Signal name */

/* GPIO_EMC_13 (number 2), SEMC_BA0/U14[20] */
/* Routed pin properties */
#define BOARD_SEMC_BA0_PERIPHERAL                                         LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_BA0_SIGNAL                                                SDI   /*!< Signal name */

/* GPIO_EMC_14 (number 1), SEMC_BA1/U14[21] */
/* Routed pin properties */
#define BOARD_SEMC_BA1_PERIPHERAL                                         LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_BA1_SIGNAL                                               PCS1   /*!< Signal name */

/* GPIO_EMC_02 (number 16), SEMC_D2/U14[5] */
/* Routed pin properties */
#define BOARD_SEMC_D2_PERIPHERAL                                          LPI2C1   /*!< Peripheral name */
#define BOARD_SEMC_D2_SIGNAL                                                 SCL   /*!< Signal name */

/* GPIO_EMC_03 (number 15), SEMC_D3/U14[7] */
/* Routed pin properties */
#define BOARD_SEMC_D3_PERIPHERAL                                          LPI2C1   /*!< Peripheral name */
#define BOARD_SEMC_D3_SIGNAL                                                 SDA   /*!< Signal name */

/* GPIO_AD_B0_10 (number 98), ENET_RXD0/U11[16]/J19[6] */
/* Routed pin properties */
#define BOARD_LED1_PERIPHERAL                                               PWM2   /*!< Peripheral name */
#define BOARD_LED1_SIGNAL                                                      A   /*!< Signal name */
#define BOARD_LED1_CHANNEL                                                    2U   /*!< Signal channel */

/* GPIO_AD_B0_14 (number 94), ENET_TXD0/U11[24]/J17[7] */
/* Routed pin properties */
#define BOARD_LED2_PERIPHERAL                                               PWM2   /*!< Peripheral name */
#define BOARD_LED2_SIGNAL                                                      A   /*!< Signal name */
#define BOARD_LED2_CHANNEL                                                    0U   /*!< Signal channel */

/* GPIO_AD_B0_15 (number 93), ENET_TXD1/U11[25]/J19[2] */
/* Routed pin properties */
#define BOARD_LED3_PERIPHERAL                                               PWM2   /*!< Peripheral name */
#define BOARD_LED3_SIGNAL                                                      B   /*!< Signal name */
#define BOARD_LED3_CHANNEL                                                    0U   /*!< Signal channel */

/* GPIO_EMC_07 (number 10), SEMC_D7/U14[13] */
/* Routed pin properties */
#define BOARD_SEMC_D7_PERIPHERAL                                            ENC1   /*!< Peripheral name */
#define BOARD_SEMC_D7_SIGNAL                                               PHASE   /*!< Signal name */
#define BOARD_SEMC_D7_CHANNEL                                                  A   /*!< Signal channel */

/* GPIO_EMC_09 (number 8), SEMC_WE/U14[16] */
/* Routed pin properties */
#define BOARD_SEMC_WE_PERIPHERAL                                            ENC1   /*!< Peripheral name */
#define BOARD_SEMC_WE_SIGNAL                                               PHASE   /*!< Signal name */
#define BOARD_SEMC_WE_CHANNEL                                                  B   /*!< Signal channel */

/* GPIO_EMC_05 (number 13), SEMC_D5/U14[10] */
/* Routed pin properties */
#define BOARD_ENC_Buttion_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_ENC_Buttion_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_ENC_Buttion_CHANNEL                                             5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_ENC_Buttion_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_ENC_Buttion_GPIO_PIN                                            5U   /*!< GPIO pin number */
#define BOARD_ENC_Buttion_GPIO_PIN_MASK                               (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_ENC_Buttion_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_ENC_Buttion_PIN                                                 5U   /*!< PORT pin number */
#define BOARD_ENC_Buttion_PIN_MASK                                    (1U << 5U)   /*!< PORT pin mask */

/* GPIO_AD_B0_12 (number 96), ENET_RXER/U11[20]/J19[4] */
/* Routed pin properties */
#define BOARD_ENET_RXER_PERIPHERAL                                          ADC1   /*!< Peripheral name */
#define BOARD_ENET_RXER_SIGNAL                                                IN   /*!< Signal name */
#define BOARD_ENET_RXER_CHANNEL                                               0U   /*!< Signal channel */

/* GPIO_AD_B0_08 (number 100), ENET_TX_CLK/U11[9] */
/* Routed pin properties */
#define BOARD_ENET_TX_CLK_PERIPHERAL                                      LPI2C3   /*!< Peripheral name */
#define BOARD_ENET_TX_CLK_SIGNAL                                             SCL   /*!< Signal name */

/* GPIO_AD_B0_09 (number 99), ENET_RXD1/U11[15]/J17[3] */
/* Routed pin properties */
#define BOARD_ENET_RXD1_PERIPHERAL                                        LPI2C3   /*!< Peripheral name */
#define BOARD_ENET_RXD1_SIGNAL                                               SDA   /*!< Signal name */

/* GPIO_AD_B1_13 (number 76), CAN_STBY/J18[4] */
/* Routed pin properties */
#define BOARD_CAN_STBY_PERIPHERAL                                        FLEXIO1   /*!< Peripheral name */
#define BOARD_CAN_STBY_SIGNAL                                                 IO   /*!< Signal name */
#define BOARD_CAN_STBY_CHANNEL                                                2U   /*!< Signal channel */

/* GPIO_AD_B1_06 (number 84), ENET_INT/U11[21]/J17[8] */
/* Routed pin properties */
#define BOARD_ENET_INT_PERIPHERAL                                        FLEXIO1   /*!< Peripheral name */
#define BOARD_ENET_INT_SIGNAL                                                 IO   /*!< Signal name */
#define BOARD_ENET_INT_CHANNEL                                                9U   /*!< Signal channel */

/* GPIO_AD_B1_02 (number 90), SAI1_TX_SYNC/J19[10] */
/* Routed pin properties */
#define BOARD_CAM_PWDN_PERIPHERAL                                          GPIO1   /*!< Peripheral name */
#define BOARD_CAM_PWDN_SIGNAL                                            gpio_io   /*!< Signal name */
#define BOARD_CAM_PWDN_CHANNEL                                               18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_CAM_PWDN_GPIO                                                GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_CAM_PWDN_GPIO_PIN                                              18U   /*!< GPIO pin number */
#define BOARD_CAM_PWDN_GPIO_PIN_MASK                                 (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_CAM_PWDN_PORT                                                GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_CAM_PWDN_PIN                                                   18U   /*!< PORT pin number */
#define BOARD_CAM_PWDN_PIN_MASK                                      (1U << 18U)   /*!< PORT pin mask */

/* GPIO_AD_B1_03 (number 89), SAI1_TXD/J19[9] */
/* Routed pin properties */
#define BOARD_CAM_RES_PERIPHERAL                                           GPIO1   /*!< Peripheral name */
#define BOARD_CAM_RES_SIGNAL                                             gpio_io   /*!< Signal name */
#define BOARD_CAM_RES_CHANNEL                                                19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_CAM_RES_GPIO                                                 GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_CAM_RES_GPIO_PIN                                               19U   /*!< GPIO pin number */
#define BOARD_CAM_RES_GPIO_PIN_MASK                                  (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_CAM_RES_PORT                                                 GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_CAM_RES_PIN                                                    19U   /*!< PORT pin number */
#define BOARD_CAM_RES_PIN_MASK                                       (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B1_04 (number 88), AUD_INT */
/* Routed pin properties */
#define BOARD_CAM_VS_PERIPHERAL                                            GPIO1   /*!< Peripheral name */
#define BOARD_CAM_VS_SIGNAL                                              gpio_io   /*!< Signal name */
#define BOARD_CAM_VS_CHANNEL                                                 20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_CAM_VS_GPIO                                                  GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_CAM_VS_GPIO_PIN                                                20U   /*!< GPIO pin number */
#define BOARD_CAM_VS_GPIO_PIN_MASK                                   (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_CAM_VS_PORT                                                  GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_CAM_VS_PIN                                                     20U   /*!< PORT pin number */
#define BOARD_CAM_VS_PIN_MASK                                        (1U << 20U)   /*!< PORT pin mask */

/* GPIO_AD_B1_05 (number 87), SAI1_RXD */
/* Routed pin properties */
#define BOARD_CAM_HS_PERIPHERAL                                          FLEXIO1   /*!< Peripheral name */
#define BOARD_CAM_HS_SIGNAL                                                   IO   /*!< Signal name */
#define BOARD_CAM_HS_CHANNEL                                                 10U   /*!< Signal channel */

/* GPIO_AD_B1_07 (number 83), SD0_VSELECT/J19[1] */
/* Routed pin properties */
#define BOARD_CAM_XCLK_PERIPHERAL                                           PWM1   /*!< Peripheral name */
#define BOARD_CAM_XCLK_SIGNAL                                                  B   /*!< Signal name */
#define BOARD_CAM_XCLK_CHANNEL                                                0U   /*!< Signal channel */

/* GPIO_SD_B0_01 (number 47), SD1_D3/J15[2] */
/* Routed pin properties */
#define BOARD_SD1_D3_PERIPHERAL                                           USDHC1   /*!< Peripheral name */
#define BOARD_SD1_D3_SIGNAL                                           usdhc_data   /*!< Signal name */
#define BOARD_SD1_D3_CHANNEL                                                  3U   /*!< Signal channel */

/* GPIO_SD_B0_00 (number 48), SD1_D2/J15[1] */
/* Routed pin properties */
#define BOARD_SD1_D2_PERIPHERAL                                           USDHC1   /*!< Peripheral name */
#define BOARD_SD1_D2_SIGNAL                                           usdhc_data   /*!< Signal name */
#define BOARD_SD1_D2_CHANNEL                                                  2U   /*!< Signal channel */

/* GPIO_SD_B0_04 (number 43), SD1_D0/J15[7] */
/* Routed pin properties */
#define BOARD_SD1_D0_PERIPHERAL                                           USDHC1   /*!< Peripheral name */
#define BOARD_SD1_D0_SIGNAL                                           usdhc_data   /*!< Signal name */
#define BOARD_SD1_D0_CHANNEL                                                  0U   /*!< Signal channel */

/* GPIO_SD_B0_02 (number 46), SD1_CMD/J15[3] */
/* Routed pin properties */
#define BOARD_SD1_CMD_PERIPHERAL                                          USDHC1   /*!< Peripheral name */
#define BOARD_SD1_CMD_SIGNAL                                           usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B0_03 (number 45), SD1_CLK/J15[5] */
/* Routed pin properties */
#define BOARD_SD1_CLK_PERIPHERAL                                          USDHC1   /*!< Peripheral name */
#define BOARD_SD1_CLK_SIGNAL                                           usdhc_clk   /*!< Signal name */

/* GPIO_SD_B0_05 (number 42), SD1_D1/J15[8] */
/* Routed pin properties */
#define BOARD_SD1_D1_PERIPHERAL                                           USDHC1   /*!< Peripheral name */
#define BOARD_SD1_D1_SIGNAL                                           usdhc_data   /*!< Signal name */
#define BOARD_SD1_D1_CHANNEL                                                  1U   /*!< Signal channel */

/* GPIO_SD_B0_06 (number 41), SD_CD_SW/J15[9] */
/* Routed pin properties */
#define BOARD_SD_CD_SW_PERIPHERAL                                         USDHC1   /*!< Peripheral name */
#define BOARD_SD_CD_SW_SIGNAL                                         usdhc_cd_b   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
